### ISSUE TITLE
Error when running

### ISSUE THREAD

**Issue by tlindgren** [wogong/dayone-to-roam#1]
Thanks for creating this script. When I run it, I'm gettin this error:

File "dayone-to-roam.py", line 14
    def __init__(self, jsonpath: Path) -> None:

Can you give me any hints about what I might be missing? 

Thanks, 

Tim

**Comment by wogong** [comment]
Make sure you have Python 3.6 or higher version.

**Comment by tlindgren** [comment]
I have python@3.8: stable 3.8.5 - using Homebrew on a Mac. Getting the same error

**Comment by jamesmarq** [comment]
I have the same issue. Tim - were you able to resolve? Thanks!
